### ISSUE TITLE
Tracking issue for 0.6.0

### ISSUE THREAD

**Issue by Bunogi** [Bunogi/darkredis#11]
This is a tracking issue for 0.6.0. The following changes have to be made before release:
- [x] Streaming CommandList responses (#9)
- [x] Make `CommandList` a list of `Result`s instead of wrapping the whole thing in one
- [x] Allow user to provide serialization buffer (#6)
- [x] Drop `ConnectionPool` in favour of an adapter crate for [`deadpool`](https://github.com/bikeshedder/deadpool) (#3. This will no longer block 0.6.0's release) 
- [x] Convenience functions for hash sets
- [x] Take generic password type (#1)
- [x] Fix broken documentation links
- [x] Change or remove the `runtime_agnostic` feature to reflect that it's using async-std's runtime

**Comment by Bunogi** [comment]
Closing after the release of 0.6.0
